# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: git clone https://github.com/galloj/IFJ22_Tester.git tests

      - name: Install dependencies
        run: sudo apt-get -y install valgrind

      - name: make
        run: |
         cd src
         make
         ../tests/test.py ./ifj22_compiler ./ic22int

      - name: valgrind
        run: |
          cd src
          valgrind --leak-check=yes ./ifj22_compiler < ../code-examples/factorial-recursive
